name: Pytest

on: [push, pull_request]

env:
  DB_PASSWORD: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -e .[dev]
    - name: Run tests
      run: pytest tests
